pipeline {
    agent any
    stages {
        stage('Checkout') { steps { checkout scm } }
        stage('UI Automation') { steps { dir('02_Web_Automation') { bat 'mvn clean test' } } }
        stage('API Automation') { steps { dir('03_API_Testing/RestAssured') { bat 'mvn clean test' } } }
    }
    post {
        always { archiveArtifacts artifacts: '**/target/surefire-reports/**/*', allowEmptyArchive: true }
    }
}
